#!/bin/bash
##############################################################
##  This script is used for AWS core functions + logic      ##
##############################################################

main(){
	[ ${#BIOLOCKJ_TEST_MODE} -gt 0 ] && printf "\n ---------> Execute CMD [  launch_aws $(echo ${@})  ]\n"
	
	take_standard_biolockj_args "$@"
	assign_main_arg
	
	if ifArgUsed $PRECHECK ; then 
		exit_with_message "argument \"--$PRECHECK\" is not currently support when running on AWS"
	fi
	
	if ifArgUsed $GUI_ARG ; then
		exit_after_command run_aws_gui
	else
		[ ${#configFile} -eq 0 ] && exit_script "Error [ biolockj ]: AWS pipelines require a config file."
		[ ! -f $configFile ] && exit_script "Error [ biolockj ]: Config file \"$configFile\" is not found on the filesystem."
		exit_after_command run_aws $configFile
	fi
}

. ${BLJ_SCRIPT}/blj_user_arg_lib
. ${BLJ_SCRIPT}/aws_functions

main $@
